/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IFHE, IFHEInterface } from "../../../contracts/interfaces/IFHE";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "ciphertextHandles",
        type: "bytes32[]",
      },
    ],
    name: "fhe_max",
    outputs: [
      {
        internalType: "bytes32",
        name: "winnerHandle",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFHE__factory {
  static readonly abi = _abi;
  static createInterface(): IFHEInterface {
    return new Interface(_abi) as IFHEInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFHE {
    return new Contract(address, _abi, runner) as unknown as IFHE;
  }
}
