/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuctionManager {
  export type AuctionMetaStruct = {
    seller: AddressLike;
    nftContract: AddressLike;
    tokenId: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    maxBidders: BigNumberish;
    minDepositWei: BigNumberish;
  };

  export type AuctionMetaStructOutput = [
    seller: string,
    nftContract: string,
    tokenId: bigint,
    startTime: bigint,
    endTime: bigint,
    maxBidders: bigint,
    minDepositWei: bigint
  ] & {
    seller: string;
    nftContract: string;
    tokenId: bigint;
    startTime: bigint;
    endTime: bigint;
    maxBidders: bigint;
    minDepositWei: bigint;
  };
}

export interface AuctionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionCount"
      | "auctions"
      | "createAuction"
      | "encryptedAuction"
      | "getAuction"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AuctionCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedAuction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuction",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAuction", data: BytesLike): Result;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [auctionId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [auctionId: bigint, seller: string];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuctionManager extends BaseContract {
  connect(runner?: ContractRunner | null): AuctionManager;
  waitForDeployment(): Promise<this>;

  interface: AuctionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionCount: TypedContractMethod<[], [bigint], "view">;

  auctions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        seller: string;
        nftContract: string;
        tokenId: bigint;
        startTime: bigint;
        endTime: bigint;
        maxBidders: bigint;
        minDepositWei: bigint;
      }
    ],
    "view"
  >;

  createAuction: TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      maxBidders: BigNumberish,
      minDepositWei: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  encryptedAuction: TypedContractMethod<[], [string], "view">;

  getAuction: TypedContractMethod<
    [auctionId: BigNumberish],
    [AuctionManager.AuctionMetaStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        seller: string;
        nftContract: string;
        tokenId: bigint;
        startTime: bigint;
        endTime: bigint;
        maxBidders: bigint;
        minDepositWei: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      maxBidders: BigNumberish,
      minDepositWei: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptedAuction"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAuction"
  ): TypedContractMethod<
    [auctionId: BigNumberish],
    [AuctionManager.AuctionMetaStructOutput],
    "view"
  >;

  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;

  filters: {
    "AuctionCreated(uint256,address)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
  };
}
