/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auctionBids"
      | "auctions"
      | "confidentialProtocolId"
      | "createAuction"
      | "finalizeAuctionWithAdapter"
      | "getBidCiphertext"
      | "getBidCount"
      | "getWinnerCiphertext"
      | "manager"
      | "nextAuctionId"
      | "revealWinner"
      | "setFHEAdapter"
      | "setManager"
      | "submitEncryptedBid"
      | "submitFinalizedWinner"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionConfigured"
      | "AuctionFinalized"
      | "EncryptedBidSubmitted"
      | "ManagerUpdated"
      | "WinnerRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auctionBids",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAuctionWithAdapter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidCiphertext",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnerCiphertext",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextAuctionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealWinner",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFHEAdapter",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedBid",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFinalizedWinner",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuctionWithAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidCiphertext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBidCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnerCiphertext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextAuctionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFHEAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFinalizedWinner",
    data: BytesLike
  ): Result;
}

export namespace AuctionConfiguredEvent {
  export type InputTuple = [auctionId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [auctionId: bigint, seller: string];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionFinalizedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winnerCiphertext: BytesLike
  ];
  export type OutputTuple = [auctionId: bigint, winnerCiphertext: string];
  export interface OutputObject {
    auctionId: bigint;
    winnerCiphertext: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EncryptedBidSubmittedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidIndex: BigNumberish,
    bidder: AddressLike
  ];
  export type OutputTuple = [
    auctionId: bigint,
    bidIndex: bigint,
    bidder: string
  ];
  export interface OutputObject {
    auctionId: bigint;
    bidIndex: bigint;
    bidder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerUpdatedEvent {
  export type InputTuple = [newManager: AddressLike];
  export type OutputTuple = [newManager: string];
  export interface OutputObject {
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerRevealedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    amountWei: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    amountWei: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    amountWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedAuction extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedAuction;
  waitForDeployment(): Promise<this>;

  interface: EncryptedAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auctionBids: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        ciphertext: string;
        bidder: string;
        commitment: string;
        deposit: bigint;
      }
    ],
    "view"
  >;

  auctions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string,
        string
      ] & {
        seller: string;
        nftContract: string;
        tokenId: bigint;
        startTime: bigint;
        endTime: bigint;
        maxBidders: bigint;
        minDepositWei: bigint;
        finalized: boolean;
        winnerCiphertext: string;
        winner: string;
        fheAdapter: string;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createAuction: TypedContractMethod<
    [
      seller: AddressLike,
      nftContract: AddressLike,
      tokenId: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      maxBidders: BigNumberish,
      minDepositWei: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  finalizeAuctionWithAdapter: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBidCiphertext: TypedContractMethod<
    [auctionId: BigNumberish, index: BigNumberish],
    [string],
    "view"
  >;

  getBidCount: TypedContractMethod<[auctionId: BigNumberish], [bigint], "view">;

  getWinnerCiphertext: TypedContractMethod<
    [auctionId: BigNumberish],
    [string],
    "view"
  >;

  manager: TypedContractMethod<[], [string], "view">;

  nextAuctionId: TypedContractMethod<[], [bigint], "view">;

  revealWinner: TypedContractMethod<
    [auctionId: BigNumberish, winner: AddressLike, amountWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFHEAdapter: TypedContractMethod<
    [auctionId: BigNumberish, adapter: AddressLike],
    [void],
    "nonpayable"
  >;

  setManager: TypedContractMethod<
    [newManager: AddressLike],
    [void],
    "nonpayable"
  >;

  submitEncryptedBid: TypedContractMethod<
    [
      auctionId: BigNumberish,
      ciphertextHandle: BytesLike,
      inputProof: BytesLike,
      commitment: BytesLike
    ],
    [void],
    "payable"
  >;

  submitFinalizedWinner: TypedContractMethod<
    [auctionId: BigNumberish, winnerCiphertext: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auctionBids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        ciphertext: string;
        bidder: string;
        commitment: string;
        deposit: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string,
        string
      ] & {
        seller: string;
        nftContract: string;
        tokenId: bigint;
        startTime: bigint;
        endTime: bigint;
        maxBidders: bigint;
        minDepositWei: bigint;
        finalized: boolean;
        winnerCiphertext: string;
        winner: string;
        fheAdapter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [
      seller: AddressLike,
      nftContract: AddressLike,
      tokenId: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      maxBidders: BigNumberish,
      minDepositWei: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeAuctionWithAdapter"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBidCiphertext"
  ): TypedContractMethod<
    [auctionId: BigNumberish, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBidCount"
  ): TypedContractMethod<[auctionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWinnerCiphertext"
  ): TypedContractMethod<[auctionId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "manager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextAuctionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealWinner"
  ): TypedContractMethod<
    [auctionId: BigNumberish, winner: AddressLike, amountWei: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFHEAdapter"
  ): TypedContractMethod<
    [auctionId: BigNumberish, adapter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setManager"
  ): TypedContractMethod<[newManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitEncryptedBid"
  ): TypedContractMethod<
    [
      auctionId: BigNumberish,
      ciphertextHandle: BytesLike,
      inputProof: BytesLike,
      commitment: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "submitFinalizedWinner"
  ): TypedContractMethod<
    [auctionId: BigNumberish, winnerCiphertext: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuctionConfigured"
  ): TypedContractEvent<
    AuctionConfiguredEvent.InputTuple,
    AuctionConfiguredEvent.OutputTuple,
    AuctionConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "AuctionFinalized"
  ): TypedContractEvent<
    AuctionFinalizedEvent.InputTuple,
    AuctionFinalizedEvent.OutputTuple,
    AuctionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "EncryptedBidSubmitted"
  ): TypedContractEvent<
    EncryptedBidSubmittedEvent.InputTuple,
    EncryptedBidSubmittedEvent.OutputTuple,
    EncryptedBidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerUpdated"
  ): TypedContractEvent<
    ManagerUpdatedEvent.InputTuple,
    ManagerUpdatedEvent.OutputTuple,
    ManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerRevealed"
  ): TypedContractEvent<
    WinnerRevealedEvent.InputTuple,
    WinnerRevealedEvent.OutputTuple,
    WinnerRevealedEvent.OutputObject
  >;

  filters: {
    "AuctionConfigured(uint256,address)": TypedContractEvent<
      AuctionConfiguredEvent.InputTuple,
      AuctionConfiguredEvent.OutputTuple,
      AuctionConfiguredEvent.OutputObject
    >;
    AuctionConfigured: TypedContractEvent<
      AuctionConfiguredEvent.InputTuple,
      AuctionConfiguredEvent.OutputTuple,
      AuctionConfiguredEvent.OutputObject
    >;

    "AuctionFinalized(uint256,bytes)": TypedContractEvent<
      AuctionFinalizedEvent.InputTuple,
      AuctionFinalizedEvent.OutputTuple,
      AuctionFinalizedEvent.OutputObject
    >;
    AuctionFinalized: TypedContractEvent<
      AuctionFinalizedEvent.InputTuple,
      AuctionFinalizedEvent.OutputTuple,
      AuctionFinalizedEvent.OutputObject
    >;

    "EncryptedBidSubmitted(uint256,uint256,address)": TypedContractEvent<
      EncryptedBidSubmittedEvent.InputTuple,
      EncryptedBidSubmittedEvent.OutputTuple,
      EncryptedBidSubmittedEvent.OutputObject
    >;
    EncryptedBidSubmitted: TypedContractEvent<
      EncryptedBidSubmittedEvent.InputTuple,
      EncryptedBidSubmittedEvent.OutputTuple,
      EncryptedBidSubmittedEvent.OutputObject
    >;

    "ManagerUpdated(address)": TypedContractEvent<
      ManagerUpdatedEvent.InputTuple,
      ManagerUpdatedEvent.OutputTuple,
      ManagerUpdatedEvent.OutputObject
    >;
    ManagerUpdated: TypedContractEvent<
      ManagerUpdatedEvent.InputTuple,
      ManagerUpdatedEvent.OutputTuple,
      ManagerUpdatedEvent.OutputObject
    >;

    "WinnerRevealed(uint256,address,uint256)": TypedContractEvent<
      WinnerRevealedEvent.InputTuple,
      WinnerRevealedEvent.OutputTuple,
      WinnerRevealedEvent.OutputObject
    >;
    WinnerRevealed: TypedContractEvent<
      WinnerRevealedEvent.InputTuple,
      WinnerRevealedEvent.OutputTuple,
      WinnerRevealedEvent.OutputObject
    >;
  };
}
